// <auto-generated />
namespace BlackMarket_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChangeSliderEntity_AddSliderNumber_DeleteOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeSliderEntity_AddSliderNumber_DeleteOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "202206231653193_ChangeSliderEntity_AddSliderNumber_DeleteOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
