// <auto-generated />
namespace BlackMarket_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChangeRefreshTokenEntity_ChangeClientIdColumnTypeToString_30 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeRefreshTokenEntity_ChangeClientIdColumnTypeToString_30));
        
        string IMigrationMetadata.Id
        {
            get { return "202206271915356_ChangeRefreshTokenEntity_ChangeClientIdColumnTypeToString_30"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
